config/routes.rb
Tblazersfans::Application.routes.draw do

get "game_recaps/:id/mail" => "game_recaps#mail", :as => 'mail_recap'

get "game_recaps/:id/spam" => "game_recaps#spam", :as => 'spam_recap'

  resources :highlights

  resources :game_recaps do

    collection { post :import}

    get 'recaps/:page', :action => :index, :on => :collection

  end

  resources :stories

  devise_for :ballers

  resources :recappers do

    collection { post :import}

    get 'recaps/:page', :action => :index, :on => :collection

  end

  get "contact_us" => "page#contact_us"
  post "contact_us" => "page#contact_us"

  get "home" => "page#home"
  get "news" => "page#news"
  get "forum" => "page#forum"
  get "recaps" => "page#recaps"
  get "store" => "page#store"
  get "calendar" => "page#calendar"

  get "home/mail" => "home#mail", :as =>'mail_contact'

  get "page/recaps17_18"
  get "page/recaps16_17"
  get "page/recaps15_16"
  get "page/recaps14_15"
  get "page/recaps13_14"
  get "page/recaps12_13"

  get 'recaps15_16/page/:page', :to => 'page#recaps15_16'
  get 'recaps14_15/page/:page', :to => 'page#recaps14_15'
  get 'recaps13_14/page/:page', :to => 'page#recaps13_14'

  get 'recaps12_13/page/:page', :to => 'page#recaps12_13'

  get "page/store"

   root 'page#home'

  

end

app/views/page/calendar.html.erb
<h1>Boxscores &amp; Game Calendar</h1>
<% calendar_color="" %>
<div id="calendar">
  <h2 id="month">
  <%= link_to "<", date: @date.prev_month %>
    <%= @date.strftime("%B %Y") %> <%= link_to ">", date: @date.next_month %></h2>


  <%= calendar @date do |datey| %>
      <%versus_or_at="" %>

      <%= datey.day %>
      <% if @season15_16_by_date[datey.strftime("%Y-%m-%d")] %>


      <ul>
        <% @season15_16_by_date[datey.strftime("%Y-%m-%d")].each do |matchup| %>

            <% if matchup.h_initials=='POR' %>
                <% calendar_color='home_key' %>


                <% if matchup.htotal.to_i > matchup.atotal.to_i %>
                <%win_or_loss="W" %>

                <% elsif matchup.htotal.to_i < matchup.atotal.to_i %>
                <% win_or_loss="L" %>


                    <% end %>


            <% end %>

            <% if matchup.a_initials=='POR' %>
                <% calendar_color='away_key' %>
                <% if matchup.atotal.to_i > matchup.htotal.to_i %>
                    <%win_or_loss="W" %>
                    <% elsif matchup.atotal.to_i < matchup.htotal.to_i%>
                    <%win_or_loss="L" %>


                <% end %>

            <%end %>


        <li class="<%=calendar_color %>"><%= link_to (""+matchup.a_initials+" "+ matchup.atotal+"<br/> @ <br/>"+ matchup.h_initials+" "+ matchup.htotal+"<br/>"+win_or_loss.to_s).html_safe, matchup %></li>
        <%end %>

      </ul>

      <%end%>

  <% end %>

</div>
<br/>
<br/>
<div id="calendar_key">
  <h2>calendar key</h2>
  <table>
    <tr><td><div class="todays_date">Today</div></td></tr><tr><td><div class="home_key"><span href="" class="uk-icon-justify uk-icon-home"></span>Home</div></td></tr><tr><td><div class="away_key"><span href="" class="uk-icon-justify uk-icon-plane"></span>Away</div></td></tr>

  </table>

</div>

app/views/page/contact.html.erb
<div id="news_show_organize3">
<!--<h2>contact us</h2>-->
  <% if ! @submitted || @form_error %>
      <h1 class="typical_headers">Contact Us</h1>
      <%= @error_msg %>
      <%= form_for contact_path, :class => "contact_form", :controller =>"page", :action => "mail_contact", :method => "POST" do %>
          <br/>
          <%= label_tag :name, "Enter Your Full Name: " %>
          <%= text_field_tag :name, @name, :autofocus => "autofocus", :placeholder => "Enter your name" %><br/><br/>

          <%= label_tag :email, "Enter Your Valid Email Address: " %>
          <%= email_field_tag :email, @email, :placeholder => "you@domain.com" %><br/><br/>
          <%= label_tag :phone, "Enter Your Phone : " %>
          <%= phone_field_tag :phone, @phone, :placeholder => "555-555-5555" %><br/>  <br/>
          <%= label_tag :question, "Please Enter Your Question(s), Comment(s) or Concern(s): " %>  <br/> <br/>
          <%= text_area_tag :question, @question, :size => "70x10" %>
          <br/>
          <br/>
          <%= check_box_tag :newsletter, "newsletter", @newsletter %>
          <%= label_tag :newsletter, "Subscribe To Our Newsletter?" %><br/> <br/>
          <%= check_box_tag :song, "song", @song %>
          <%= label_tag :song, "Free Song?" %><br/> <br/>
          <%= label_tag @contact, "Preferred Method of Contact: " %>
          <%= radio_button_tag :contact, "Phone", @phone %>   <%= label_tag @phone, "Phone" %>
          <%= radio_button_tag :contact, "Email", @email_method %> <%= label_tag @email_method, "Email" %><br/> <br/>

          <br/>


          <br/>
          <br/>
          <div id="submit_it">
            <%= submit_tag "Mail" %>
          </div>
          <br/>
          <br/>
      <% end %>
      <br/>
      <br/>
  <% else %>
      <h1 class="typical_headers">Thanks for your info!</h1>
      <div id="contact_recap">

        <span class="recap_format"><p>Here's a quick recap of what you submitted: </p></span>
        <p><span class="recap_format">Your Name:</span> <%= @name %> </p>
        <p><span class="recap_format">Your Email Address:</span> <%= @email %> </p>
        <p><span class="recap_format">Your Phone #:</span> <%= @phone %> </p>
        <p><span class="recap_format">Your Question/Comment/Concern:</span> <%= @question %> </p>
        <p><span class="recap_format">Newsletter :</span> <%= @newsletter %> </p>
        <p><span class="recap_format">Free Song :</span> <%= @song %> </p>
        <p><span class="recap_format">Preferred Contact :</span> <%= @contact %> </p>
      </div>
      <br/>
      <br/>
  <% end %>
<br/>

</div>

app/views/page/contact_us.html.erb
<div id="news_show_organize3">
  <!--<h2>contact us</h2>-->
  <% if ! @submitted || @form_error %>
      <h1 class="typical_headers">Contact Us</h1>
      <%= @error_msg %>
      <%= form_for contact_us_path, :class => "contact_form", :controller =>"page", :action => "mail_contact", :method => "POST" do %>
          <br/>
          <%= label_tag :name, "Enter Your Full Name: " %>
          <%= text_field_tag :name, @name, :autofocus => "autofocus", :placeholder => "Enter your name" %><br/><br/>

          <%= label_tag :email, "Enter Your Valid Email Address: " %>
          <%= email_field_tag :email, @email, :placeholder => "you@domain.com" %><br/><br/>
          <%= label_tag :phone, "Enter Your Phone : " %>
          <%= phone_field_tag :phone, @phone, :placeholder => "555-555-5555" %><br/>  <br/>
          <%= label_tag :question, "Please Enter Your Question(s), Comment(s) or Concern(s): " %>  <br/> <br/>
          <%= text_area_tag :question, @question, :size => "70x10" %>
          <br/>
          <br/>
          <%= check_box_tag :newsletter, "newsletter", @newsletter %>
          <%= label_tag :newsletter, "Subscribe To Our Newsletter?" %><br/> <br/>
          <%= check_box_tag :song, "song", @song %>
          <%= label_tag :song, "Free Song?" %><br/> <br/>
          <%= label_tag @contact, "Preferred Method of Contact: " %>
          <%= radio_button_tag :contact, "Phone", @phone %>   <%= label_tag @phone, "Phone" %>
          <%= radio_button_tag :contact, "Email", @email_method %> <%= label_tag @email_method, "Email" %><br/> <br/>

          <br/>


          <br/>
          <br/>
          <div id="submit_it">
            <%= submit_tag "Mail" %>
          </div>
          <br/>
          <br/>
      <% end %>
      <br/>
      <br/>
  <% else %>
      <h1 class="typical_headers">Thanks for your info!</h1>
      <div id="contact_recap">

        <span class="recap_format"><p>Here's a quick recap of what you submitted: </p></span>
        <p><span class="recap_format">Your Name:</span> <%= @name %> </p>
        <p><span class="recap_format">Your Email Address:</span> <%= @email %> </p>
        <p><span class="recap_format">Your Phone #:</span> <%= @phone %> </p>
        <p><span class="recap_format">Your Question/Comment/Concern:</span> <%= @question %> </p>
        <p><span class="recap_format">Newsletter :</span> <%= @newsletter %> </p>
        <p><span class="recap_format">Free Song :</span> <%= @song %> </p>
        <p><span class="recap_format">Preferred Contact :</span> <%= @contact %> </p>
      </div>
      <br/>
      <br/>
  <% end %>
  <br/>

</div>

app/views/page/forum.html.erb
<h1>Page#forum</h1>
<p>Find me in app/views/page/forum.html.erb</p>

app/views/page/home.html.erb
<% require 'active_support'%>
<div id="news_show_organize3">
  <h2>latest games</h2>

</div>
<div class="uk-slidenav-position" data-uk-slider='{infinite: false}'>

  <div class="uk-slider-container">
    <ul class="uk-slider uk-grid-width-medium-1-4">
      <% @last_recapper2.each do |c| %>

          <% versus_or_at="" %>

          <% away_nick_dash=c.afname.parameterize+'.png' %>
          <% home_nick_dash=c.hfname.parameterize+'.png' %>




          <% if c.h_initials=='POR' %>
              <%versus_or_at="VS." %>
              <% home_or_away = c.afname.downcase+'<span class="box_total_h2"> '+c.atotal+"</span><br/>at<br/> portland trail blazers <span class='box_total_h2'>"+c.htotal+"</span>" %>


              <% if c.htotal.to_i > c.atotal.to_i %>
                  <% win_or_loss ="<span class='win_loss_box_show_win2'>W</span>" %>
              <%else %>
                  <% win_or_loss =""%>
              <%end%>
              <% if c.htotal.to_i < c.atotal.to_i %>
                  <% win_or_loss ="<span class='win_loss_box_show_loss2'>L</span>" %> <% end %>

              <li>
                <div class="uk-clearfix">
                  <table class="header_last_game">
                    <tr><th colspan="3"><%= date_format_string(c.datey.to_s) %></th></tr>
                    <tr><td><%= image_tag(home_nick_dash, style: "", class: "uk-img-preserve")%><br/> <%=c.h_initials %><br/><span class='slider_score'><%=c.htotal%></span></td><td><%= versus_or_at.html_safe%><br/><br/><%=win_or_loss.html_safe%></td><td><%= image_tag(away_nick_dash, style: "", class: "uk-img-preserve")%><br/> <%=c.a_initials %><br/><span class='slider_score'><%=c.atotal%></span></td></tr>
                    <tr><td colspan="3"><div data-uk-button-radio><%= link_to 'Box Score', c, class: "uk-button uk-button-mini" %>  </div></td></tr>
                  </table>
                </div>

              </li>

          <%else %>
          <% end %>

          <% if c.a_initials=='POR' %>
              <% versus_or_at="@" %>
              <% home_or_away ="portland trail blazers <span class='box_total_h2'>"+c.atotal+"</span> <br/>at</br> "+c.hfname.downcase+ " <span class='box_total_h2'>"+c.htotal+"</span>" %>
              <% if c.atotal.to_i > c.htotal.to_i %>

                  <% win_or_loss ="<span class='win_loss_box_show_win2'>W</span>" %>
              <%end%>

              <% if c.atotal.to_i < c.htotal.to_i %>
                  <% win_or_loss ="<span class='win_loss_box_show_loss2'>L</span>" %>
              <% end %>
              <li>
                <div class="uk-clearfix">
                  <table class="header_last_game">
                    <tr><th colspan="3"><%= date_format_string(c.datey) %></th></tr>
                    <tr><td><%= image_tag(away_nick_dash, style: "", class: "uk-img-preserve")%><br/> <%=c.a_initials %><br/><span class='slider_score'><%=c.atotal%></span></td><td><%= versus_or_at.html_safe%><br/><br/><%=win_or_loss.html_safe%></td><td><%= image_tag(home_nick_dash, style: "", class: "uk-img-preserve")%><br/> <%=c.h_initials %><br/><span class='slider_score'><%=c.htotal%></span></td></tr>
                    <tr><td colspan="3"><div data-uk-button-radio><%= link_to 'Box Score', c, class: "uk-button uk-button-mini" %>  </div></td></tr>
                  </table>
                </div>
              </li>
          <% else %>

          <% end %>

      <% end %>

    </ul>
  </div>


  <a href="" class="uk-slidenav uk-slidenav-contrast uk-slidenav-previous" data-uk-slider-item="previous"></a>
  <a href="" class="uk-slidenav uk-slidenav-contrast uk-slidenav-next" data-uk-slider-item="next"></a>

</div>
<br/>
<div id="boxscore_buttons">
  <%= link_to 'All 2017-2018 Boxcores', page_recaps17_18_path, class: "uk-button uk-button" %>
  <%= link_to 'All Historical Boxscores', game_recaps_path, class: "uk-button uk-button" %>
</div>


<hr>

<% @last_articles.each do |x| %>
    <% date_time2 =Time.parse(x.date.to_s) %>
    <article class="uk-article">
      <h1 class="uk-article-title"><%= link_to x.title, x, class: "uk-article-title-a" %></h1>
      <p class="uk-article-meta"><%= "written by "+x.author %> <br/><%=" on "+ date_time2.strftime("%B #{date_time2.day.ordinalize} %Y ") %> </p>
      <p class="uk-clearfix">
        <% story=(x.story.html_safe.to_s)
           story2=strip_tags(story)
        %>
           <%= image_tag(x.image.url, class: "uk-thumbnail-medium uk-align-medium-right" ) %>
        <span class="article-texterson"><%= sanitize(story2, :tags=>[]).truncate(100, :separator => " ").html_safe%></span>
        <br/>
        <br/>

        <%= link_to 'Continue Reading', x, class: "uk-button uk-button-danger" %>
        <a class="uk-button" href="#"># <span href="" class="uk-icon-justify uk-icon-comment"></span></a>

      </p>

    </article>
<%end%>
<hr>

<div id="news_show_organize4">
<h2><span class="clip-city">clip city<span href="" class="uk-icon-justify uk-icon-film"></span></span></h2>


<div class="uk-slidenav-position" data-uk-slider='{infinite: false}'>

  <div class="uk-slider-container">
    <ul class="uk-slider uk-grid-width-medium-1-4">
      <% @last_videos.each do |x| %>
      <li>






        <figure class="uk-overlay uk-overlay-hover">
         <div><%=x.image.html_safe%></div>
          <figcaption class="uk-overlay-top uk-overlay-slide-top"> <%=x.title%></figcaption>
        </figure>

      </li>
      <% end %>
          </ul>

  </div>

  <a href="" class="uk-slidenav uk-slidenav-contrast uk-slidenav-previous" data-uk-slider-item="previous"></a>
  <a href="" class="uk-slidenav uk-slidenav-contrast uk-slidenav-next" data-uk-slider-item="next"></a>

</div>
</div>

app/views/page/news.html.erb
<h1>Page#news</h1>
<p>Find me in app/views/page/news.html.erb</p>

app/views/page/recaps.html.erb
<h1>Page#recaps</h1>
<p>Find me in app/views/page/recaps.html.erb</p>

Testiclese testiclese

app/views/page/store.html.erb
<h1>Page#store</h1>
<p>Find me in app/views/page/store.html.erb</p>