config/routes.rb
Tblazersfans::Application.routes.draw do

get "game_recaps/:id/mail" => "game_recaps#mail", :as => 'mail_recap'

get "game_recaps/:id/spam" => "game_recaps#spam", :as => 'spam_recap'

  resources :highlights

  resources :game_recaps do

    collection { post :import}

    get 'recaps/:page', :action => :index, :on => :collection

  end

  resources :stories

  devise_for :ballers

  resources :recappers do

    collection { post :import}

    get 'recaps/:page', :action => :index, :on => :collection

  end

  get "contact_us" => "page#contact_us"
  post "contact_us" => "page#contact_us"

  get "home" => "page#home"
  get "news" => "page#news"
  get "forum" => "page#forum"
  get "recaps" => "page#recaps"
  get "store" => "page#store"
  get "calendar" => "page#calendar"

  get "home/mail" => "home#mail", :as =>'mail_contact'

  get "page/recaps17_18"
  get "page/recaps16_17"
  get "page/recaps15_16"
  get "page/recaps14_15"
  get "page/recaps13_14"
  get "page/recaps12_13"

  get 'recaps15_16/page/:page', :to => 'page#recaps15_16'
  get 'recaps14_15/page/:page', :to => 'page#recaps14_15'
  get 'recaps13_14/page/:page', :to => 'page#recaps13_14'

  get 'recaps12_13/page/:page', :to => 'page#recaps12_13'

  get "page/store"

   root 'page#home'

  

end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessor :image
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @stories = Story.all
    respond_with(@stories)
  end

  def show
    respond_with(@story)
  end

  def new
    @story = Story.new
    respond_with(@story)
  end

  def edit
  end

  def create
    @story = Story.new(story_params)
    @story.save
    respond_with(@story)
  end

  def update
    @story.update(story_params)
    respond_with(@story)
  end

  def destroy
    @story.destroy
    respond_with(@story)
  end

  private
    def set_story
      @story = Story.find(params[:id])
    end

    def story_params
      params.require(:story).permit(:title, :author, :date, :story, :caption, :image, :published, :main_story)
    end
end

app/views/stories/_form.html.erb
<%= tinymce %>
<%= form_for(@story, :html => {:multipart => true}) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :story %><br>
    <%= f.text_area :story, class:"tinymce" %>
  </div>
  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </div>

    <div class="field">
    <%= f.label :image %><br>


      <%= f.file_field :image %>
      <br/>
      <br/>

      Current Image:
      <%= image_tag(@story.image.url, class: "uk-thumbnail-mini" ) %>
  </div>

    <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label :main_story %><br>
    <%= f.check_box :main_story %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Date</th>
      <th>Story</th>
      <% if is_admin? %>
      <th></th>
      <th></th>
          <%else %>

          <% end %>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.author %></td>
        <td><%= date_format_string(story.date) %></td>
        <td><%= link_to 'Show', story %></td>
        <% if is_admin? %>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      <%else %>

        <%end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if is_admin? %>
<%= link_to 'New Story', new_story_path %>

<% else %>

<% end %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>
<% date_time =Time.parse(@story.date.to_s) %>

<div id="news_show_organize3">
  <h2><%= @story.title %><br/><span class="uk-article-meta">by <%= @story.author %><br/><%= date_time.strftime("%B #{date_time.day.ordinalize} %Y ")%></h2></span>

  <%= image_tag @story.image.url, class: "uk-thumbnail uk-align-center" %>
  <p>
    <strong>Caption:</strong>
    <%= @story.caption %>
  </p>



  <%= @story.story.html_safe %>
  <br/>
  <br/>

  <% if current_baller.try(:admin?) %>
  <%= link_to 'Edit', edit_story_path(@story) %> |&nbsp;
  <%else %>

  <% end %>
  <%= link_to 'Back to Stories (Future News)', stories_path %>&nbsp; |
  <%= link_to 'Home', home_path %>
</div>

<!--<p>-->
  <!--<strong>Title:</strong>-->
  <!--<%= @story.title %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>Author:</strong>-->
  <!--<%= @story.author %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>Date:</strong>-->
  <!--<%= @story.date %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>Story:</strong>-->
  <!--<%= @story.story %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>Caption:</strong>-->
  <!--<%= @story.caption %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>Image:</strong>-->

  <!--<%= image_tag @story.image.url, class: "uk-thumbnail-medium" %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>Published:</strong>-->
  <!--<%= @story.published %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>Main story:</strong>-->
  <!--<%= @story.main_story %>-->
<!--</p>-->