config/routes.rb
Tblazersfans::Application.routes.draw do

get "game_recaps/:id/mail" => "game_recaps#mail", :as => 'mail_recap'

get "game_recaps/:id/spam" => "game_recaps#spam", :as => 'spam_recap'

  resources :highlights

  resources :game_recaps do

    collection { post :import}

    get 'recaps/:page', :action => :index, :on => :collection

  end

  resources :stories

  devise_for :ballers

  resources :recappers do

    collection { post :import}

    get 'recaps/:page', :action => :index, :on => :collection

  end

  get "contact_us" => "page#contact_us"
  post "contact_us" => "page#contact_us"

  get "home" => "page#home"
  get "news" => "page#news"
  get "forum" => "page#forum"
  get "recaps" => "page#recaps"
  get "store" => "page#store"
  get "calendar" => "page#calendar"

  get "home/mail" => "home#mail", :as =>'mail_contact'

  get "page/recaps17_18"
  get "page/recaps16_17"
  get "page/recaps15_16"
  get "page/recaps14_15"
  get "page/recaps13_14"
  get "page/recaps12_13"

  get 'recaps15_16/page/:page', :to => 'page#recaps15_16'
  get 'recaps14_15/page/:page', :to => 'page#recaps14_15'
  get 'recaps13_14/page/:page', :to => 'page#recaps13_14'

  get 'recaps12_13/page/:page', :to => 'page#recaps12_13'

  get "page/store"

   root 'page#home'

  

end

app/models/highlight.rb
class Highlight < ActiveRecord::Base
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  before_action :set_highlight, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @highlights = Highlight.all
    respond_with(@highlights)
  end

  def show
    respond_with(@highlight)
  end

  def new
    @highlight = Highlight.new
    respond_with(@highlight)
  end

  def edit
  end

  def create
    @highlight = Highlight.new(highlight_params)
    @highlight.save
    respond_with(@highlight)
  end

  def update
    @highlight.update(highlight_params)
    respond_with(@highlight)
  end

  def destroy
    @highlight.destroy
    respond_with(@highlight)
  end

  private
    def set_highlight
      @highlight = Highlight.find(params[:id])
    end

    def highlight_params
      params.require(:highlight).permit(:title, :date, :caption, :image)
    end
end

app/helpers/highlights_helper.rb
module HighlightsHelper
end

app/views/highlights/_form.html.erb
<%= form_for(@highlight) do |f| %>
  <% if @highlight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@highlight.errors.count, "error") %> prohibited this highlight from being saved:</h2>

      <ul>
      <% @highlight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label "YouTube Embed Iframe" %><br>
    <p>Change iframe proportion to: width: 240 and height: 180</p>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/highlights/edit.html.erb
<h1>Editing highlight</h1>

<%= render 'form' %>

<%= link_to 'Show', @highlight %> |
<%= link_to 'Back', highlights_path %>

app/views/highlights/index.html.erb
<h1>Listing highlights</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Caption</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @highlights.each do |highlight| %>
      <tr>
        <td><%= highlight.title %></td>
        <td><%= highlight.date %></td>
        <td><%= highlight.caption %></td>
        <td><%= highlight.image %></td>
        <td><%= link_to 'Show', highlight %></td>
        <td><%= link_to 'Edit', edit_highlight_path(highlight) %></td>
        <td><%= link_to 'Destroy', highlight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Highlight', new_highlight_path %>

app/views/highlights/new.html.erb
<h1>New highlight</h1>

<%= render 'form' %>

<%= link_to 'Back', highlights_path %>

app/views/highlights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @highlight.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @highlight.date %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @highlight.caption %>
</p>

<p>
  <strong>Image:</strong>
  <%= @highlight.image %>
</p>

<%= link_to 'Edit', edit_highlight_path(@highlight) %> |
<%= link_to 'Back', highlights_path %>